language: ruby
rvm:
 - 2.3.0

before_script:
 - chmod +x travis.sh

script: ./travis.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - gh-pages
    - next

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 42c3959ac0237e24d48b54e6f7aefb2b7f44bf42
  keep-history: true
  on:
    repo: sushobhana/sushobhana.github.io
    branches:    # ← new!
      only:      # ← new!
        - master # ← new!
